name: compose-oci

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  compose-oci:
    uses: openads-project/openads-dev-environment/.github/workflows/compose-oci.yml@main
    secrets: inherit
